# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 011377d96ab23cddc854dc328a8d6caa6aaf8711747d7d46599b0d389225448afff13ffea688ce5b656f764ee263b5d75cc9627687ecfdefe2394f1e52d9d0a1

test:
  secret_key_base: 8a8bfccaa016acce94434400db2cf0373e4ed4e712aa43a058625d939ff541e1a9dd2e883b3f5ff49e7562abd5e9128a97dbef8921b9d3255898f3cb0c5fa972

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
